name: ssh-to-runner-container
on: push

jobs:
  ssh-runner-docker:
    runs-on: ubuntu-latest
    container: circleci/ruby:2.6.3-node-browsers-legacy

    env:
      PGHOST: postgres
      PGUSER: sapling
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:10.1-alpine
        env:
          POSTGRES_USER: sapling
          POSTGRES_DB: sapling_test
          POSTGRES_PASSWORD: ""
        ports:
        - 5432:5432
        # Add a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
      Browser:
        image: circleci/node:10-browsers

    steps:
    - uses: actions/checkout@v1
    - name: Try Build
      run: ./not-exist-file.sh it bloke build    
    - name: Start SSH via Ngrok
      if: ${{ failure() }}
      run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
      env:
      # After sign up on the https://ngrok.com/
      # You can find this token here: https://dashboard.ngrok.com/get-started/setup
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      #NGROK_TOKEN: 1cu2nQXxljrX4mNGxz4z9N1QSfm_3JDS7Ek4Rti6oTwov43Sx

      # This password you will use when authorizing via SSH 
        USER_PASS: ${{ secrets.PASSPHRASE }}
      #USER_PASS: murAmur
    - name: Don't kill instace
      if: ${{ failure() }}
      run: sleep 1h  
    - name: log ruby version
      run: |
        ruby -v
        cat /etc/os-release      
          