name: Actions Workflow

on : [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-16.04
    steps:
    - name: List files
      run: |
        ls -la
        pwd
        echo $GITHUB_SHA 
        echo $GITHUB_REPOSITORY
        echo $GITHUB_WORKSPACE 
        echo "${{ github.token }}"
        git clone git@github:lakshmojirao999/github-action-test  
    - name: Checkout
      uses: actions/checkout@v1    
    - name: List files
      run: |
        ls -la
        pwd
  
    - name: Simple JS Actions
      id: greet
      uses: actions/hello-world-javascript-action@v1
      with: 
        who-to-greet: Lakshmoji
    - name: Log Greeting Time
      run : echo "${{ steps.greet.outputs.time }}"    
    
        