name: Actions Workflow

on : [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Checkout cloudspot repo
      uses: actions/checkout@v1
      with:
        repository: cloudnativeready/cloudspot
        path: cloudspot
        ref: master  
    - name: List files
      run: |
        ls -la
        pwd
        echo $GITHUB_SHA 
        echo $GITHUB_REPOSITORY
        echo $GITHUB_WORKSPACE 
        echo "${{ github.token }}"   
    - name: Simple JS Actions
      id: greet
      uses: actions/hello-world-javascript-action@v1
      with: 
        who-to-greet: Lakshmoji
    - name: Log Greeting Time
      run : echo "${{ steps.greet.outputs.time }}"    
    
        