name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-16.04
    container: 
      image: node:14.8.0-alpine3.10
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release
      - name: Create applocatipn config
      #   env:
      #     CONFIG: lakshmoji
        run: | 
          echo "lakshmoji" >> application.json       
          ls -la





      