name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-16.04
    container: 
      image: node:14.8.0-alpine3.10
    strategy:
      fail-fast: false
      matrix:
        # Set N number of parallel jobs you want to run tests on.
        # Use higher number if you have slow tests to split them on more parallel jobs.
        # Remember to update ci_node_index below to 0..N-1
        ci_node_total: [8]
        # set N-1 indexes for parallel jobs
        # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
        ci_node_index: [0, 1, 2, 3, 4, 5, 6, 7]      
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release
      - name: Create applocatipn config
      #   env:
      #     CONFIG: lakshmoji
        run: | 
          json='{"ENV": {} }'
          echo $json > application.json       
          ls -la
          cat application.json
      - name: Update etc/hosts
        run: |
          echo 127.0.0.1 foo.frontend.me > /etc/hosts
          cat /etc/hosts   







      