name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-16.04
    container: circleci/ruby:2.6.3-node-browsers-legacy
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     # Set N number of parallel jobs you want to run tests on.
    #     # Use higher number if you have slow tests to split them on more parallel jobs.
    #     # Remember to update ci_node_index below to 0..N-1
    #     ci_node_total: [8]
    #     # set N-1 indexes for parallel jobs
    #     # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
    #     ci_node_index: [0, 1, 2, 3, 4, 5, 6, 7]      
    steps:
      # - name: Setup file system permissions
      #   run: |
      #     sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/ 

      - name: log ruby version
        run: |
          ruby -v
          cat /etc/os-release
      
      - name: Create applocatipn config
        run: | 
          json='{"ENV": {} }'
          echo $json > application.json       
          ls -la
          cat application.json
      
      - name: Update etc/hosts
        run: |
          sudo echo 127.0.0.1 foo.frontend.me > /etc/hosts
          cat /etc/hosts  
      
      # - name: Setup Code Climate test-reporter
      #   run: |
      #       curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #       chmod +x ./cc-test-reporter

      # - name: Code Climate before-build
      #   run: |
      #     ./cc-test-reporter before-build

                     









      