name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-16.04
    container: 
      image: node:14.8.0-alpine3.10
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release
      - name: Create applocatipn config
      #   env:
      #     CONFIG: lakshmoji
        run: | 
          json='{"ENV": {} }'
          echo $json > application.json       
          ls -la
          cat application.json
          echo echo 127.0.0.1 foo.frontend.me | sudo tee -a /etc/hosts 






      