on : pull_request
#on: [push, pull_request]

jobs:
  functions:
    runs-on: ubuntu-16.04
    steps:
      - name: dump function
        run: |
          echo ${{ contains('hello','ll') }}
          echo ${{ startsWith('hello','he') }}
          echo ${{ endsWith('hello','lo') }}
          echo ${{ format('hello {0} {1} {2}','world','!','!') }}
  one:
    runs-on: ubuntu-16.04
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: eccho "$GITHUB_CONTEXT"
      - name: Dump job context
        if: failure()
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        if: always()
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: eccho "$RUNNER_CONTEXT"
        continue-on-error: true  #continue on error
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"