name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-16.04
    container: 
      image: node:14.8.0-alpine3.10
    steps:
      - name: log node version
        run: |
          node -v
          cat /etc/os-release
      - name: Create applocatipn config
      #   env:
      #     CONFIG: lakshmoji
        run: | 
          json='{"ENV": "b8f2b8b", "environment": "test", "tags_at_commit": "sometags", "project": "someproject", "current_date": "09/10/2014", "version": "someversion"}'
          echo $json > application.json       
          ls -la
          cat application.json






      