name: Matrix
on : push

jobs: 
  node-version:
    runs-on: ubuntu-16.04
    steps:
      - name: log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: New Node version
        run: node -v    

### strategy
  node-version-strategy:
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]
        node_version: [6,7,10]
    #  max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: New Node version
        run: node -v  