name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-16.04
    container: 
      image: node:14.8.0-alpine3.10
    steps:
    - name: Start SSH via Ngrok
      if: ${{ failure() }}
      run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
      env:
      # After sign up on the https://ngrok.com/
      # You can find this token here: https://dashboard.ngrok.com/get-started/setup
      NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      #NGROK_TOKEN: 1cu2nQXxljrX4mNGxz4z9N1QSfm_3JDS7Ek4Rti6oTwov43Sx

      # This password you will use when authorizing via SSH 
      USER_PASS: ${{ secrets.PASSPHRASE }}
      #USER_PASS: murAmur
    - name: log node version
      run: |
        node -v
        cat /etc/os-release
